export {default as Hero} from './Hero.jsx'
export {default as NavBar} from './NavBar'
export {default as Services} from './Services'
export {default as Testimonials} from './Testimonials'
export {default as About} from './About'
export {default as CallToAction} from './Call-to-action'
export {default as ChooseUsSection} from './ChooseUsSection'
export {default as Footer} from './Footer.jsx'